oc_platform:
    #resource: "@OCPlatformBundle/Controller/"
    resource: '@OCPlatformBundle/Resources/config/routing.yml'
    #type:     annotation
    prefix:   /

un_helper:
    resource: "@unHelperBundle/Controller/"
    type:     annotation
    prefix:   /

un_blog:
    resource: "@unBlogBundle/Controller/"
    type:     annotation
    prefix:   /

un:
    resource: "@unBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
